# Generated by Django 2.2.6 on 2019-11-18 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('description', models.TextField(max_length=200, verbose_name='描述')),
                ('app_url', models.TextField(max_length=200, verbose_name='平台地址')),
                ('redirect_url', models.TextField(max_length=200, verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': 'platform',
                'verbose_name_plural': 'platforms',
                'db_table': 'home_platform',
            },
            managers=[
                ('objects', home.models.PlatformManager()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('platforms', models.ManyToManyField(blank=True, to='home.Platform', verbose_name='platforms')),
            ],
            options={
                'verbose_name': 'platform_groups',
                'verbose_name_plural': 'platform_groups',
                'db_table': 'home_platform_groups',
            },
            managers=[
                ('objects', home.models.PlatformGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_groups', models.ManyToManyField(blank=True, help_text='The platform_groups this user belongs to. A user will get all platforms granted to each of their platform_groups.', related_name='user_profile_set', related_query_name='user_profile', to='home.PlatformGroup', verbose_name='platform_groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'home_user_profile',
            },
        ),
    ]
