# Generated by Django 2.2.6 on 2019-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icon_url',
            field=models.CharField(default='', max_length=200, verbose_name='图标地址'),
        ),
    ]
