# Generated by Django 2.2.6 on 2019-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_platform_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon_url',
            field=models.TextField(default='', max_length=200, verbose_name='图标地址'),
        ),
    ]
